name: Content Generation Pipeline

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '48 4 * * *'
    - cron: '36 9 * * *'
    - cron: '24 14 * * *'
    - cron: '12 19 * * *'
  workflow_dispatch:

jobs:
  content-generation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
          cache: 'npm'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas openai pillow numpy

      # 1. Download keyword search file
      - name: Download kw_search.pyc
        run: python core/scripts/kw_request.pyc

      # 2. Run kw_search.pyc
      - name: Run keyword generator
        run: python core/github/kw_search.pyc

      # 3. Delete kw_search.pyc
      - name: Delete kw_search.pyc
        run: python core/scripts/kw_delete.pyc

      # 4. Download script AGC AI file
      - name: Download script_agc_ai.pyc
        run: python core/scripts/script_request.pyc

      # 5. Run script_agc_ai.pyc
      - name: Run AGC Article Generator
        run: python core/github/script_agc_ai.pyc

      # 6. Delete script_agc_ai.pyc
      - name: Delete script_agc_ai.pyc
        run: python core/scripts/script_delete.pyc

      # 7. Download image generator file
      - name: Download image_generator.pyc
        run: python core/scripts/image_request.pyc

      # 8. Run image_generator.pyc
      - name: Run image generator
        run: python core/github/image_generator.pyc

      # 9. Delete image_generator.pyc
      - name: Delete image_generator.pyc
        run: python core/scripts/image_delete.pyc

      # 10. Build
      - name: Build with Hugo
        run: npm run build

      # 11. Deploy
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          full_commit_message: "Auto-deploy updated content"